app/src/Entity/Title.php
<?php

namespace App\Entity;

use App\Repository\TitleRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TitleRepository::class)
 * @ORM\Table(name="titles")
 */
class Title
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="smallint")
     */
    private $year;

    /**
     * @ORM\Column(type="string", columnDefinition="enum('G', 'PG', 'PG-13', 'PG-17+', 'R+')")
     */
    private $age_rating;

    /**
     * @ORM\Column(type="string", columnDefinition="enum('anime', 'manga', 'ranobe')")
     */
    private $type;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $uri_alias;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getAgeRating(): ?string
    {
        return $this->age_rating;
    }

    public function setAgeRating(string $age_rating): self
    {
        $this->age_rating = $age_rating;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getPageUri(): ?string
    {
        return '/' . $this->getType() . '/' . $this->getUriAlias();
    }

    public function getPosterUrl(): string
    {
        return '/img/covers/placeholder.jpg';
    }

    public function getUriAlias(): ?string
    {
        return $this->uri_alias;
    }

    public function setUriAlias(string $uri_alias): self
    {
        $this->uri_alias = $uri_alias;
        return $this;
    }
}

app/src/Controller/SiteController.php
<?php

namespace App\Controller;

use App\Frontend\Breadcrumb;
use App\Repository\ArticleRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class SiteController extends AbstractController
{

    /**
     * @Route("/", name="index")
     */
    public function index(ArticleRepository $repo): Response
    {
        $articles = $repo->findAll();
        return $this->render('site/index.html.twig', [
            'articles' => $articles,
        ]);
    }

    /**
     * @Route("/anime", name="anime")
     */
    public function anime(ArticleRepository $repo): Response
    {
        $articles = $repo->findAll();
        return $this->render('site/index.html.twig', [
            'articles' => $articles,
            'breadcrumb' => Breadcrumb::generateShort('/anime', 'Аниме'),
        ]);
    }

    /**
     * @Route("/anime/{page_uri}", name="anime_article")
     */
    public function animearticle($page_uri, ArticleRepository $repo): Response
    {
        $article = $repo->findOneByUriAlias($page_uri);
        return $this->render('site/article.html.twig', [
            'article' => $article,
            'breadcrumb' => Breadcrumb::generateForarticle($article),
        ]);
    }

}

app/templates/site/article.html.twig
{% extends 'site.html.twig' %}

{% block title %}{{ article.name }} ({{ article.year }}){% endblock %}

{% block content %}
    <img src="{{ article.posterUrl }}" alt="{{ article.name }} ({{ article.year }})" class="ui top aligned medium left floated image">
    <h1 style="margin-top: 0">{{ article.name }} <span style="color: #aaa"></span></h1>
    <h2>{{ article.year }}</h2>
    <div class="ui star rating" data-rating="4" data-max-rating="5" id="rating"></div>
    <h3>{{ article.ageRating }}</h3>
    <div>{{ article.description|nl2br }}</div>
    <div class="clearfix"></div>
    <script>
        $('#rating')
            .rating({
                initialRating: 2,
                maxRating: 4
            })
        ;
    </script>

    <h2>Комментарии</h2>
    <div class="ui comments">
        <div class="comment">
            <a class="avatar">
                <img src="/img/users/avatars/user-thumb.jpg">
            </a>
            <div class="content">
                <a class="author">Джо Хендерсон</a>
                <div class="metadata">
                    <div class="date">1 день назад</div>
                </div>
                <div class="text">
                    <p>Часы, минуты и секунды остаются видны, напоминая что в ваших усилиях положить их туда. </p>
                    <p>Сохраните до следующей пробежки, когда часы позволят вам увидеть, насколько непостоянны ваши усилия.</p>
                </div>
                <div class="actions">
                    <a class="reply">Reply</a>
                </div>
            </div>
        </div>
        <div class="comment">
            <a class="avatar">
                <img src="/img/users/avatars/user-thumb.jpg">
            </a>
            <div class="content">
                <a class="author">Кристиан Рока</a>
                <div class="metadata">
                    <div class="date">2 дня назад</div>
                </div>
                <div class="text">Я ретвитнул это. </div>
                <div class="actions">
                    <a class="reply">Reply</a>
                </div>
            </div>
        </div>
        <form class="ui reply form">
            <div class="field">
                <textarea></textarea>
            </div>
            <div class="ui primary submit labeled icon button"><i class="icon edit"></i> Добавить комментарий
            </div>
        </form>
    </div>

{% endblock %}

app/templates/site/index.html.twig
{% extends 'site.html.twig' %}

{% block title %}Homepage{% endblock %}

{% block content %}
    <div id="list">
        <div v-if="articles.length">
            <div class="ui link cards four column doubling stackable">
                <div v-for="article in articles" class="column card">
                    <div class="image">
                        <a v-bind:href="article.pageUri">
                            <img v-bind:src="article.posterUrl" class="ui fluid image"/>
                        </a>
                    </div>
                    <div class="content">
                        <div class="header">${ article.name }$</div>
                        {#
                        <div class="meta">${ article.type }$</div>
                        #}
                        <div class="description" style="height: 100px; overflow-y: hidden">
                            ${ article.description }$
                        </div>
                    </div>
                    <div class="extra content">
                        <span class="right floated">${ article.year }$</span>
                        <span><i class="user icon"></i> ${ article.ageRating }$ </span>
                    </div>
                </div>
            </div>
        </div>
        <div v-else>

            <br>
            <br>
            <div class="ui active inverted dimmer">
                <div class="ui text loader">Загрузка</div>
            </div>
            <br>
            <br>

        </div>
    </div>

    <script>
        const ListApp = {
            delimiters: ['${', '}$'],
            data() {
                return {
                    articles: []
                }
            },
            mounted() {

            }
        }

        const vueApp = Vue.createApp(ListApp).mount('#list')

        restApi.get('article/list', function (response) {
            if (response && response.ok) {
                vueApp.articles = response.list;
            }
        });

    </script>

{% endblock %}

app/templates/site/title.html.twig
{% extends 'site.html.twig' %}

{% block title %}{{ title.name }} ({{ title.year }}){% endblock %}

{% block content %}
    <img src="{{ title.posterUrl }}" alt="{{ title.name }} ({{ title.year }})" class="ui top aligned medium left floated image">
    <h1 style="margin-top: 0">{{ title.name }} <span style="color: #aaa"></span></h1>
    <h2>{{ title.year }}</h2>
    <div class="ui star rating" data-rating="4" data-max-rating="5" id="rating"></div>
    <h3>{{ title.ageRating }}</h3>
    <div>{{ title.description|nl2br }}</div>
    <div class="clearfix"></div>
    <script>
        $('#rating')
            .rating({
                initialRating: 2,
                maxRating: 4
            })
        ;
    </script>

    <h2>Комментарии</h2>
    <div class="ui comments">
        <div class="comment">
            <a class="avatar">
                <img src="/img/users/avatars/user-thumb.jpg">
            </a>
            <div class="content">
                <a class="author">Джо Хендерсон</a>
                <div class="metadata">
                    <div class="date">1 день назад</div>
                </div>
                <div class="text">
                    <p>Часы, минуты и секунды остаются видны, напоминая что в ваших усилиях положить их туда. </p>
                    <p>Сохраните до следующей пробежки, когда часы позволят вам увидеть, насколько непостоянны ваши усилия.</p>
                </div>
                <div class="actions">
                    <a class="reply">Reply</a>
                </div>
            </div>
        </div>
        <div class="comment">
            <a class="avatar">
                <img src="/img/users/avatars/user-thumb.jpg">
            </a>
            <div class="content">
                <a class="author">Кристиан Рока</a>
                <div class="metadata">
                    <div class="date">2 дня назад</div>
                </div>
                <div class="text">Я ретвитнул это. </div>
                <div class="actions">
                    <a class="reply">Reply</a>
                </div>
            </div>
        </div>
        <form class="ui reply form">
            <div class="field">
                <textarea></textarea>
            </div>
            <div class="ui primary submit labeled icon button"><i class="icon edit"></i> Добавить комментарий
            </div>
        </form>
    </div>

{% endblock %}